// DO NOT EDIT THIS FILE

import 'shiny';
import 'jquery';

export const handleUtils = () => {
	Shiny.addCustomMessageHandler('leprechaun-show', (msg) => {
		$(msg.selector).show();
	});

	Shiny.addCustomMessageHandler('leprechaun-hide', (msg) => {
		$(msg.selector).hide();
	});

	Shiny.addCustomMessageHandler('leprechaun-toggle', (msg) => {
		$(msg.selector).toggle();
	});

	Shiny.addCustomMessageHandler('leprechaun-disable', (msg) => {
		$(msg.selector).prop('disabled', true);
	});

	Shiny.addCustomMessageHandler('leprechaun-enable', (msg) => {
		$(msg.selector).prop('disabled', false);
	});

	Shiny.addCustomMessageHandler('leprechaun-disable-selectize', (msg) => {
		let sel = $(msg.selector).selectize();
		sel[0].selectize.disable();
	});

	Shiny.addCustomMessageHandler('leprechaun-enable-selectize', (msg) => {
		let sel = $(msg.selector).selectize();
		sel[0].selectize.enable();
	});
	
	Shiny.addCustomMessageHandler('leprechaun-eval', (msg) => {
		eval(msg.code);
	});
	
}