#---------------------------------------------#
# DO NOT EDIT THIS FILE OR ADD ANYTHING TO IT #
#---------------------------------------------#

#' Dependencies
#' 
#' @importFrom htmltools htmlDependency
#' 
#' @keywords internal
serveAssets <- function(){
	# JavaScript files
	javascript <- list.files(
		"inst", 
		recursive = TRUE, 
		pattern = ".js$"
	)

	# CSS files
	css <- list.files(
		"inst",
		recursive = TRUE,
		pattern = ".css$"
	)
	
	# so dependency processes correctly
	names(css) <- rep("file", length(css))
	names(javascript) <- rep("file", length(javascript))

	# serve dependencies
	htmlDependency(
		"#PKGNAME#",
		version = utils::packageVersion("#PKGNAME#"),
		package = "#PKGNAME#",
		src = ".",
		script = javascript,
		stylesheet = css
	)
}
