#---------------------------------------------#
# DO NOT EDIT THIS FILE OR ADD ANYTHING TO IT #
#---------------------------------------------#

#' Create a Helper to Send Messages
#' 
#' Create a function to send custom messages to the front-end,
#' this function makes it such that the namespace is carried
#' along.
#' 
#' @param session Shiny session to derive namespace
#' 
#' @examples 
#' \dontrun{
#' send_message <- make_send_message(session)
#' send_message("do-sth")
#' send_message("do-sth-else", x = 1)
#' }
#' 
#' @noRd 
#' @keywords internal
make_send_message <- function(session){
  ns <- session$ns(NULL)

  function(msgId, ...){
    session$sendCustomMessage(
      msgId,
      list(
        ns = ns,
        ...
      )
    )
  }
}
