#---------------------------------------------#
# DO NOT EDIT THIS FILE OR ADD ANYTHING TO IT #
#---------------------------------------------#

.onLoad <- function(...){
	shiny::addResourcePath(
		"img",
		system.file("img", package = "#PKGNAME#")
	)
}